### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by jose2007kj** [javebratt/debtTracker#1]
sir ... thanks a lot  for this rc1 updated project 
i am getting the folowing message while npm install.........
UNMET PEER DEPENDENCY @angular/compiler@2.1.0
UNMET PEER DEPENDENCY @angular/core@2.1.0
UNMET PEER DEPENDENCY @angular/platform-server@2.1.0
 UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12

sir i get the following after doing npm install

`mtech@coddlab:~/Downloads/debtTracker-master$ npm install
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> node-sass@3.9.3 install /home/mtech/Downloads/debtTracker-master/node_modules/node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.9.3/linux-x64-48_binding.node
Binary downloaded and installed at /home/mtech/Downloads/debtTracker-master/node_modules/node-sass/vendor/linux-x64-48/binding.node

> node-sass@3.9.3 postinstall /home/mtech/Downloads/debtTracker-master/node_modules/node-sass
> node scripts/build.js

"/home/mtech/Downloads/debtTracker-master/node_modules/node-sass/vendor/linux-x64-48/binding.node" exists. 
 testing binary.
Binary is fine; exiting.
ionic-hello-world@ /home/mtech/Downloads/debtTracker-master
+-- @angular/common@2.1.0 
+-- UNMET PEER DEPENDENCY @angular/compiler@2.1.0
+-- @angular/compiler-cli@0.6.4 
| +-- @angular/tsc-wrapped@0.3.0 
| | `-- tsickle@0.1.7 
| |   `-- source-map-support@0.3.3 
| |     `-- source-map@0.1.32 
| +-- minimist@1.2.0 
| +-- parse5@2.2.2 
| `-- reflect-metadata@0.1.8 
+-- UNMET PEER DEPENDENCY @angular/core@2.1.0
+-- @angular/forms@2.1.0 
+-- @angular/http@2.1.0 
+-- @angular/platform-browser@2.1.0 
+-- @angular/platform-browser-dynamic@2.1.0 
+-- UNMET PEER DEPENDENCY @angular/platform-server@2.1.0
+-- @ionic/app-scripts@0.0.34 
| +-- autoprefixer@6.4.1 
| | +-- browserslist@1.3.6 
| | +-- caniuse-db@1.0.30000559 
| | +-- normalize-range@0.1.2 
| | +-- num2fraction@1.2.2 
| | `-- postcss-value-parser@3.3.0 
| +-- chalk@1.1.3 
| | +-- ansi-styles@2.2.1 
| | +-- escape-string-regexp@1.0.5 
| | +-- has-ansi@2.0.0 
| | | `-- ansi-regex@2.0.0 
| | +-- strip-ansi@3.0.1 
| | `-- supports-color@2.0.0 
| +-- chokidar@1.6.0 
| | +-- anymatch@1.3.0 
| | | +-- arrify@1.0.1 
| | | `-- micromatch@2.3.11 
| | |   +-- arr-diff@2.0.0 
| | |   | `-- arr-flatten@1.0.1 
| | |   +-- array-unique@0.2.1 
| | |   +-- braces@1.8.5 
| | |   | +-- expand-range@1.8.2 
| | |   | | `-- fill-range@2.2.3 
| | |   | |   +-- is-number@2.1.0 
| | |   | |   +-- isobject@2.1.0 
| | |   | |   | `-- isarray@1.0.0 
| | |   | |   `-- randomatic@1.1.5 
| | |   | +-- preserve@0.2.0 
| | |   | `-- repeat-element@1.1.2 
| | |   +-- expand-brackets@0.1.5 
| | |   | `-- is-posix-bracket@0.1.1 
| | |   +-- extglob@0.3.2 
| | |   +-- filename-regex@2.0.0 
| | |   +-- kind-of@3.0.4 
| | |   | `-- is-buffer@1.1.4 
| | |   +-- normalize-path@2.0.1 
| | |   +-- object.omit@2.0.0 
| | |   | +-- for-own@0.1.4 
| | |   | | `-- for-in@0.1.6 
| | |   | `-- is-extendable@0.1.1 
| | |   +-- parse-glob@3.0.4 
| | |   | +-- glob-base@0.3.0 
| | |   | `-- is-dotfile@1.0.2 
| | |   `-- regex-cache@0.4.3 
| | |     +-- is-equal-shallow@0.1.3 
| | |     `-- is-primitive@2.0.0 
| | +-- async-each@1.0.1 
| | +-- glob-parent@2.0.0 
| | +-- inherits@2.0.3 
| | +-- is-binary-path@1.0.1 
| | | `-- binary-extensions@1.7.0 
| | +-- is-glob@2.0.1 
| | | `-- is-extglob@1.0.0 
| | +-- path-is-absolute@1.0.1 
| | `-- readdirp@2.1.0 
| |   +-- readable-stream@2.1.5 
| |   | +-- buffer-shims@1.0.0 
| |   | +-- core-util-is@1.0.2 
| |   | +-- isarray@1.0.0 
| |   | +-- process-nextick-args@1.0.7 
| |   | `-- string_decoder@0.10.31 
| |   `-- set-immediate-shim@1.0.1 
| +-- clean-css@3.4.19 
| | +-- commander@2.8.1 
| | | `-- graceful-readlink@1.0.1 
| | `-- source-map@0.4.4 
| |   `-- amdefine@1.0.0 
| +-- cross-spawn@4.0.0 
| | +-- lru-cache@4.0.1 
| | | +-- pseudomap@1.0.2 
| | | `-- yallist@2.0.0 
| | `-- which@1.2.11 
| |   `-- isexe@1.1.2 
| +-- fs-extra@0.30.0 
| | +-- graceful-fs@4.1.9 
| | +-- jsonfile@2.4.0 
| | +-- klaw@1.3.0 
| | `-- rimraf@2.5.4 
| +-- magic-string@0.16.0 
| | `-- vlq@0.2.1 
| +-- node-sass@3.9.3 
| | +-- async-foreach@0.1.3 
| | +-- cross-spawn@3.0.1 
| | +-- gaze@1.1.2 
| | | `-- globule@1.0.0 
| | |   `-- glob@7.0.6 
| | +-- get-stdin@4.0.1 
| | +-- glob@7.1.1 
| | | +-- fs.realpath@1.0.0 
| | | +-- inflight@1.0.6 
| | | | `-- wrappy@1.0.2 
| | | `-- once@1.4.0 
| | +-- in-publish@2.0.0 
| | +-- lodash.clonedeep@4.5.0 
| | +-- meow@3.7.0 
| | | +-- camelcase-keys@2.1.0 
| | | | `-- camelcase@2.1.1 
| | | +-- decamelize@1.2.0 
| | | +-- loud-rejection@1.6.0 
| | | | +-- currently-unhandled@0.4.1 
| | | | | `-- array-find-index@1.0.2 
| | | | `-- signal-exit@3.0.1 
| | | +-- map-obj@1.0.1 
| | | +-- normalize-package-data@2.3.5 
| | | | +-- hosted-git-info@2.1.5 
| | | | +-- is-builtin-module@1.0.0 
| | | | `-- validate-npm-package-license@3.0.1 
| | | |   +-- spdx-correct@1.0.2 
| | | |   | `-- spdx-license-ids@1.2.2 
| | | |   `-- spdx-expression-parse@1.0.4 
| | | +-- object-assign@4.1.0 
| | | +-- read-pkg-up@1.0.1 
| | | | +-- find-up@1.1.2 
| | | | | `-- path-exists@2.1.0 
| | | | `-- read-pkg@1.1.0 
| | | |   +-- load-json-file@1.1.0 
| | | |   | +-- parse-json@2.2.0 
| | | |   | | `-- error-ex@1.3.0 
| | | |   | |   `-- is-arrayish@0.2.1 
| | | |   | +-- pify@2.3.0 
| | | |   | `-- strip-bom@2.0.0 
| | | |   |   `-- is-utf8@0.2.1 
| | | |   `-- path-type@1.1.0 
| | | +-- redent@1.0.0 
| | | | +-- indent-string@2.1.0 
| | | | | `-- repeating@2.0.1 
| | | | |   `-- is-finite@1.0.2 
| | | | `-- strip-indent@1.0.1 
| | | `-- trim-newlines@1.0.0 
| | +-- mkdirp@0.5.1 
| | | `-- minimist@0.0.8 
| | +-- nan@2.4.0 
| | +-- node-gyp@3.4.0 
| | | +-- fstream@1.0.10 
| | | +-- nopt@3.0.6 
| | | | `-- abbrev@1.0.9 
| | | +-- npmlog@3.1.2 
| | | +-- osenv@0.1.3 
| | | | +-- os-homedir@1.0.2 
| | | | `-- os-tmpdir@1.0.2 
| | | +-- path-array@1.0.1 
| | | | `-- array-index@1.0.0 
| | | |   +-- debug@2.2.0 
| | | |   | `-- ms@0.7.1 
| | | |   `-- es6-symbol@3.1.0 
| | | |     +-- d@0.1.1 
| | | |     `-- es5-ext@0.10.12 
| | | |       `-- es6-iterator@2.0.0 
| | | +-- semver@5.3.0 
| | | `-- tar@2.2.1 
| | |   `-- block-stream@0.0.9 
| | +-- npmlog@4.0.0 
| | | +-- are-we-there-yet@1.1.2 
| | | | +-- delegates@1.0.0 
| | | | `-- readable-stream@2.1.5 
| | | |   `-- isarray@1.0.0 
| | | +-- console-control-strings@1.1.0 
| | | +-- gauge@2.6.0 
| | | | +-- aproba@1.0.4 
| | | | +-- has-color@0.1.7 
| | | | +-- has-unicode@2.0.1 
| | | | +-- string-width@1.0.2 
| | | | | +-- code-point-at@1.0.1 
| | | | | | `-- number-is-nan@1.0.1 
| | | | | `-- is-fullwidth-code-point@1.0.0 
| | | | `-- wide-align@1.1.0 
| | | `-- set-blocking@2.0.0 
| | +-- request@2.75.0 
| | | +-- aws-sign2@0.6.0 
| | | +-- aws4@1.5.0 
| | | +-- bl@1.1.2 
| | | | `-- readable-stream@2.0.6 
| | | |   `-- isarray@1.0.0 
| | | +-- caseless@0.11.0 
| | | +-- combined-stream@1.0.5 
| | | | `-- delayed-stream@1.0.0 
| | | +-- extend@3.0.0 
| | | +-- forever-agent@0.6.1 
| | | +-- form-data@2.0.0 
| | | | `-- asynckit@0.4.0 
| | | +-- har-validator@2.0.6 
| | | | +-- commander@2.9.0 
| | | | +-- is-my-json-valid@2.15.0 
| | | | | +-- generate-function@2.0.0 
| | | | | +-- generate-object-property@1.2.0 
| | | | | | `-- is-property@1.0.2 
| | | | | +-- jsonpointer@4.0.0 
| | | | | `-- xtend@4.0.1 
| | | | `-- pinkie-promise@2.0.1 
| | | |   `-- pinkie@2.0.4 
| | | +-- hawk@3.1.3 
| | | | +-- boom@2.10.1 
| | | | +-- cryptiles@2.0.5 
| | | | +-- hoek@2.16.3 
| | | | `-- sntp@1.0.9 
| | | +-- http-signature@1.1.1 
| | | | +-- assert-plus@0.2.0 
| | | | +-- jsprim@1.3.1 
| | | | | +-- extsprintf@1.0.2 
| | | | | +-- json-schema@0.2.3 
| | | | | `-- verror@1.3.6 
| | | | `-- sshpk@1.10.1 
| | | |   +-- asn1@0.2.3 
| | | |   +-- assert-plus@1.0.0 
| | | |   +-- bcrypt-pbkdf@1.0.0 
| | | |   +-- dashdash@1.14.0 
| | | |   | `-- assert-plus@1.0.0 
| | | |   +-- ecc-jsbn@0.1.1 
| | | |   +-- getpass@0.1.6 
| | | |   | `-- assert-plus@1.0.0 
| | | |   +-- jodid25519@1.0.2 
| | | |   +-- jsbn@0.1.0 
| | | |   `-- tweetnacl@0.14.3 
| | | +-- is-typedarray@1.0.0 
| | | +-- isstream@0.1.2 
| | | +-- json-stringify-safe@5.0.1 
| | | +-- mime-types@2.1.12 
| | | | `-- mime-db@1.24.0 
| | | +-- node-uuid@1.4.7 
| | | +-- oauth-sign@0.8.2 
| | | +-- qs@6.2.1 
| | | +-- stringstream@0.0.5 
| | | +-- tough-cookie@2.3.1 
| | | `-- tunnel-agent@0.4.3 
| | `-- sass-graph@2.1.2 
| |   +-- lodash@4.9.0 
| |   `-- yargs@4.8.1 
| |     +-- cliui@3.2.0 
| |     | `-- wrap-ansi@2.0.0 
| |     +-- get-caller-file@1.0.2 
| |     +-- lodash.assign@4.2.0 
| |     +-- os-locale@1.4.0 
| |     | `-- lcid@1.0.0 
| |     |   `-- invert-kv@1.0.0 
| |     +-- require-directory@2.1.1 
| |     +-- require-main-filename@1.0.1 
| |     +-- which-module@1.0.0 
| |     +-- window-size@0.2.0 
| |     +-- y18n@3.2.1 
| |     `-- yargs-parser@2.4.1 
| |       `-- camelcase@3.0.0 
| +-- postcss@5.2.0 
| | +-- js-base64@2.1.9 
| | +-- source-map@0.5.6 
| | `-- supports-color@3.1.2 
| |   `-- has-flag@1.0.0 
| +-- rollup@0.36.3 
| | `-- source-map-support@0.4.4 
| |   `-- source-map@0.5.6 
| +-- rollup-plugin-commonjs@5.0.4 
| | +-- acorn@4.0.3 
| | +-- estree-walker@0.2.1 
| | `-- resolve@1.1.7 
| +-- rollup-plugin-json@2.0.2 
| +-- rollup-plugin-node-builtins@2.0.0 
| | +-- buffer-es6@4.9.2 
| | +-- crypto-browserify@3.11.0 
| | | +-- browserify-cipher@1.0.0 
| | | | +-- browserify-aes@1.0.6 
| | | | | `-- buffer-xor@1.0.3 
| | | | +-- browserify-des@1.0.0 
| | | | | `-- des.js@1.0.0 
| | | | |   `-- minimalistic-assert@1.0.0 
| | | | `-- evp_bytestokey@1.0.0 
| | | +-- browserify-sign@4.0.0 
| | | | +-- bn.js@4.11.6 
| | | | +-- browserify-rsa@4.0.1 
| | | | +-- elliptic@6.3.2 
| | | | | +-- brorand@1.0.6 
| | | | | `-- hash.js@1.0.3 
| | | | `-- parse-asn1@5.0.0 
| | | |   `-- asn1.js@4.8.1 
| | | +-- create-ecdh@4.0.0 
| | | +-- create-hash@1.1.2 
| | | | +-- cipher-base@1.0.3 
| | | | +-- ripemd160@1.0.1 
| | | | `-- sha.js@2.4.5 
| | | +-- create-hmac@1.1.4 
| | | +-- diffie-hellman@5.0.2 
| | | | `-- miller-rabin@4.0.0 
| | | +-- pbkdf2@3.0.9 
| | | +-- public-encrypt@4.0.0 
| | | `-- randombytes@2.0.3 
| | `-- process-es6@0.11.5 
| +-- rollup-plugin-node-globals@1.0.9 
| | `-- acorn@4.0.3 
| +-- rollup-plugin-node-resolve@2.0.0 
| | +-- browser-resolve@1.11.2 
| | `-- builtin-modules@1.1.1 
| +-- rollup-pluginutils@1.5.2 
| | `-- minimatch@3.0.3 
| |   `-- brace-expansion@1.1.6 
| |     +-- balanced-match@0.4.2 
| |     `-- concat-map@0.0.1 
| +-- tslint@3.15.1 
| | +-- colors@1.1.2 
| | +-- diff@2.2.3 
| | +-- findup-sync@0.3.0 
| | | `-- glob@5.0.15 
| | +-- optimist@0.6.1 
| | | +-- minimist@0.0.10 
| | | `-- wordwrap@0.0.3 
| | `-- underscore.string@3.3.4 
| |   +-- sprintf-js@1.0.3 
| |   `-- util-deprecate@1.0.2 
| +-- tslint-eslint-rules@1.5.0 
| | `-- doctrine@0.7.2 
| |   +-- esutils@1.1.6 
| |   `-- isarray@0.0.1 
| `-- uglify-js@2.7.3 
|   +-- async@0.2.10 
|   +-- source-map@0.5.6 
|   +-- uglify-to-browserify@1.0.2 
|   `-- yargs@3.10.0 
|     +-- camelcase@1.2.1 
|     +-- cliui@2.1.0 
|     | +-- center-align@0.1.3 
|     | | +-- align-text@0.1.4 
|     | | | +-- longest@1.0.1 
|     | | | `-- repeat-string@1.5.4 
|     | | `-- lazy-cache@1.0.4 
|     | +-- right-align@0.1.3 
|     | `-- wordwrap@0.0.2 
|     `-- window-size@0.1.0 
+-- @ionic/storage@1.1.6 
| +-- @types/localforage@0.0.30 
| +-- localforage@1.4.3 
| | `-- lie@3.0.2 
| |   +-- es3ify@0.1.4 
| |   | +-- esprima-fb@3001.1.0-dev-harmony-fb 
| |   | +-- jstransform@3.0.0 
| |   | | +-- base62@0.1.1 
| |   | | `-- source-map@0.1.31 
| |   | `-- through@2.3.8 
| |   +-- immediate@3.0.6 
| |   +-- inline-process-browser@1.0.0 
| |   | +-- falafel@1.2.0 
| |   | | +-- acorn@1.2.2 
| |   | | +-- foreach@2.0.5 
| |   | | `-- object-keys@1.0.11 
| |   | `-- through2@0.6.5 
| |   |   `-- readable-stream@1.0.34 
| |   `-- unreachable-branch-transform@0.3.0 
| |     +-- esmangle-evaluator@1.0.1 
| |     `-- recast@0.10.43 
| |       +-- ast-types@0.8.15 
| |       +-- esprima-fb@15001.1001.0-dev-harmony-fb 
| |       +-- private@0.1.6 
| |       `-- source-map@0.5.6 
| +-- localforage-cordovasqlitedriver@1.5.0 
| `-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
+-- @types/request@0.0.30 
| +-- @types/form-data@0.0.32 
| `-- @types/node@6.0.45 
+-- angularfire2@2.0.0-beta.5 
| `-- firebase@3.3.0 
|   +-- dom-storage@2.0.2 
|   +-- faye-websocket@0.9.3 
|   | `-- websocket-driver@0.6.4 
|   |   `-- websocket-extensions@0.1.1 
|   +-- jsonwebtoken@5.7.0 
|   | +-- jws@3.1.3 
|   | | +-- base64url@1.0.6 
|   | | | +-- concat-stream@1.4.10 
|   | | | | +-- inherits@2.0.1 
|   | | | | +-- readable-stream@1.1.14 
|   | | | | | +-- core-util-is@1.0.2 
|   | | | | | +-- isarray@0.0.1 
|   | | | | | `-- string_decoder@0.10.31 
|   | | | | `-- typedarray@0.0.6 
|   | | | `-- meow@2.0.0 
|   | | |   +-- camelcase-keys@1.0.0 
|   | | |   | +-- camelcase@1.2.1 
|   | | |   | `-- map-obj@1.0.1 
|   | | |   +-- indent-string@1.2.2 
|   | | |   | +-- get-stdin@4.0.1 
|   | | |   | `-- repeating@1.1.3 
|   | | |   |   `-- is-finite@1.0.1 
|   | | |   |     `-- number-is-nan@1.0.0 
|   | | |   +-- minimist@1.2.0 
|   | | |   `-- object-assign@1.0.0 
|   | | `-- jwa@1.1.3 
|   | |   +-- buffer-equal-constant-time@1.0.1 
|   | |   `-- ecdsa-sig-formatter@1.0.5 
|   | |     `-- base64-url@1.2.2 
|   | +-- ms@0.7.1 
|   | `-- xtend@4.0.1 
|   +-- rsvp@3.2.1 
|   `-- xmlhttprequest@1.8.0 
+-- firebase@3.5.0 
| +-- dom-storage@2.0.2 
| +-- faye-websocket@0.9.3 
| | `-- websocket-driver@0.6.4 
| |   `-- websocket-extensions@0.1.1 
| +-- jsonwebtoken@5.7.0 
| | +-- jws@3.1.3 
| | | +-- base64url@1.0.6 
| | | | +-- concat-stream@1.4.10 
| | | | | +-- inherits@2.0.1 
| | | | | +-- readable-stream@1.1.14 
| | | | | | +-- core-util-is@1.0.2 
| | | | | | +-- isarray@0.0.1 
| | | | | | `-- string_decoder@0.10.31 
| | | | | `-- typedarray@0.0.6 
| | | | `-- meow@2.0.0 
| | | |   +-- camelcase-keys@1.0.0 
| | | |   | +-- camelcase@1.2.1 
| | | |   | `-- map-obj@1.0.1 
| | | |   +-- indent-string@1.2.2 
| | | |   | +-- get-stdin@4.0.1 
| | | |   | `-- repeating@1.1.3 
| | | |   |   `-- is-finite@1.0.1 
| | | |   |     `-- number-is-nan@1.0.0 
| | | |   +-- minimist@1.2.0 
| | | |   `-- object-assign@1.0.0 
| | | `-- jwa@1.1.3 
| | |   +-- buffer-equal-constant-time@1.0.1 
| | |   `-- ecdsa-sig-formatter@1.0.5 
| | |     `-- base64-url@1.2.2 
| | +-- ms@0.7.1 
| | `-- xtend@4.0.1 
| +-- rsvp@3.2.1 
| `-- xmlhttprequest@1.8.0 
+-- ionic-angular@2.0.0-rc.1 
+-- ionic-native@2.2.4 
+-- ionicons@3.0.0 
+-- 
MET PEER DEPENDENCY rxjs@5.0.0-rc.1
| `-- symbol-observable@1.0.4 
+-- typescript@2.0.3 
`-- zone.js@0.6.25 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN angularfire2@2.0.0-beta.5 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/compiler@2.0.2 but none was installed.
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/platform-server@2.0.2 but none was installed.
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/core@2.0.2 but none was installed.
npm WARN @angular/http@2.1.0 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/core@2.1.0 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
 ##`

sir....where i might be going wrong....

**Comment by javebratt** [comment]
Hey @jose2007kj this is because `AngularFire2` and `Ionic2` are using different versions of Angular2, but check inside your project's `node_modules` folder, the packages do install in spite of the errors and warnings.

**Comment by jose2007kj** [comment]
thanks for your replay sir.....sorry i was little busy
